# Generated by Django 4.2.5 on 2023-10-02 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(default='No description given')),
                ('sender', models.CharField(default='System', max_length=255)),
                ('type', models.CharField(choices=[('match', 1), ('tournament', 2), ('league', 3), ('team', 4), ('support', 5), ('news', 6), ('general', 7), ('store', 8)], default='general', max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('pk1', models.IntegerField(default=0)),
                ('read', models.BooleanField(default=False)),
                ('seen', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternate_name', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(blank=True, max_length=25, null=True)),
                ('last_name', models.CharField(blank=True, max_length=25, null=True)),
                ('xp', models.PositiveSmallIntegerField(default=0)),
                ('user_verified', models.BooleanField(blank=True, default=False)),
                ('about_me', models.TextField(blank=True, default='Forever a mystery')),
                ('steamid64', models.CharField(blank=True, default='No SteamID64', max_length=255)),
                ('discord', models.CharField(blank=True, default='No Discord', max_length=255)),
                ('xbl', models.CharField(blank=True, default='No Xbox Live Linked', max_length=30)),
                ('steam', models.CharField(blank=True, default='No Steam Linked', max_length=30)),
                ('twitter_profile', models.CharField(blank=True, default='No Twitter Linked', max_length=30)),
                ('twitch_channel', models.CharField(blank=True, default='No Twitch Linked', max_length=50)),
                ('profile_picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('user_type', models.CharField(choices=[('user', 'Standard User'), ('admin', 'Admin'), ('superadmin', 'Super Admin')], default='user', max_length=10)),
                ('ip', models.CharField(default='0.0.0.0', max_length=45)),
                ('tournament_wins', models.PositiveSmallIntegerField(default=0)),
                ('dubl_tournament_wins', models.PositiveSmallIntegerField(default=0)),
                ('rank', models.PositiveSmallIntegerField(default=100)),
                ('country', django_countries.fields.CountryField(default='US', max_length=2)),
                ('email_enabled', models.BooleanField(default=True)),
                ('captain_teams', models.ManyToManyField(blank=True, related_name='profile_captain_teams', to='teams.team')),
                ('featured_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_featured_team', to='teams.team')),
                ('founder_teams', models.ManyToManyField(blank=True, related_name='profile_founder_teams', to='teams.team')),
                ('notifications', models.ManyToManyField(blank=True, related_name='user_notifications', to='profiles.notification')),
                ('player_teams', models.ManyToManyField(blank=True, related_name='profile_player_teams', to='teams.team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BannedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default='error', max_length=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banned', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
