# Generated by Django 4.2.5 on 2023-10-02 16:54

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontPageSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('subhead', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='carousel_images')),
            ],
            options={
                'verbose_name_plural': 'Front Page Slides',
            },
        ),
        migrations.CreateModel(
            name='OllySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freeze_team_invites', models.BooleanField(default=False)),
                ('disable_team_creation', models.BooleanField(default=False)),
                ('freeze_team_leaves', models.BooleanField(default=False)),
                ('freeze_team_deletion', models.BooleanField(default=False)),
                ('freeze_team_player_removal', models.BooleanField(default=False)),
                ('whats_new', ckeditor.fields.RichTextField(default='')),
            ],
            options={
                'verbose_name_plural': 'Olly Settings',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('website', models.URLField(blank=True, null=True)),
                ('twitter', models.CharField(blank=True, default='#', max_length=100)),
                ('bio', models.TextField()),
                ('logo', models.ImageField(blank=True, upload_to='partner_images')),
            ],
        ),
        migrations.CreateModel(
            name='SocialInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitchchannel', models.URLField(blank=True, null=True, verbose_name='twitch_channel')),
                ('youtubechannel', models.URLField(blank=True, null=True, verbose_name='youtube_channel')),
                ('twitterprofile', models.URLField(blank=True, null=True, verbose_name='twitter_profile')),
                ('facebookpage', models.URLField(blank=True, null=True, verbose_name='facebook_page')),
                ('instagrampage', models.URLField(blank=True, null=True, verbose_name='instagram_page')),
                ('discord', models.URLField(blank=True, null=True, verbose_name='discord_server')),
                ('stream', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'verbose_name_plural': 'Social info',
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('page_name', models.CharField(max_length=50)),
                ('content', ckeditor.fields.RichTextField(default='')),
                ('redirects', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaticInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', models.TextField(default='about us')),
                ('terms', models.TextField(default='terms of service')),
                ('block1text', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('block1link', models.URLField(blank=True, null=True)),
                ('block1_img', models.ImageField(blank=True, upload_to='carousel_images')),
                ('block2text', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('block2link', models.URLField(blank=True, null=True)),
                ('block2_img', models.ImageField(blank=True, upload_to='carousel_images')),
                ('block3text', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('block3link', models.URLField(blank=True, null=True)),
                ('block3_img', models.ImageField(blank=True, upload_to='carousel_images')),
                ('featured_tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_competence', to='competitions.competition')),
            ],
            options={
                'verbose_name_plural': 'Static info',
            },
        ),
    ]
