# Generated by Django 4.2.5 on 2023-10-03 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OllySetting',
            new_name='CoreSetting',
        ),
    ]
