# Generated by Django 4.2.5 on 2023-10-09 12:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_ollysetting_coresetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coresetting',
            options={'verbose_name_plural': 'Core Settings'},
        ),
        migrations.RenameField(
            model_name='staticinfo',
            old_name='featured_tournament',
            new_name='featured_competence',
        ),
        migrations.AlterField(
            model_name='coresetting',
            name='whats_new',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
