# Generated by Django 4.2.5 on 2023-10-10 17:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_coresetting_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coresetting',
            name='whats_new',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
