# Generated by Django 4.2.5 on 2023-10-02 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default_map', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('map_num', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MapPoolChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default map pool', max_length=255)),
                ('description', models.CharField(default='No map pool description', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('matchnum', models.SmallIntegerField(default=0)),
                ('reported', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('config_generated', models.BooleanField(default=False)),
                ('bestof', models.SmallIntegerField(choices=[(1, 'Best of 1'), (2, 'Best of 2'), (3, 'Best of 3'), (4, 'Best of 4'), (5, 'Best of 5')], default=1)),
                ('teamformat', models.SmallIntegerField(choices=[(0, '1v1'), (1, '2v2'), (2, '3v3'), (3, '4v4')], default=1)),
                ('team1reported', models.BooleanField(default=False)),
                ('team2reported', models.BooleanField(default=False)),
                ('server', models.CharField(blank=True, max_length=255, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('info', models.TextField(default='Match Info: ')),
                ('disputed', models.BooleanField(default=False)),
                ('bye_1', models.BooleanField(default=False)),
                ('bye_2', models.BooleanField(default=False)),
                ('disable_userreport', models.BooleanField(default=True)),
                ('conference_match', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'matches',
            },
        ),
        migrations.CreateModel(
            name='MatchCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MatchDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('teamproof_1', models.URLField()),
                ('teamproof_2', models.URLField(blank=True)),
                ('teamproof_3', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchid', models.PositiveIntegerField(default=0)),
                ('map', models.CharField(default='unknown', max_length=255)),
                ('team1', models.CharField(default='unknown', max_length=255)),
                ('team2', models.CharField(default='unknown', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMatchStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rounds_won', models.PositiveSmallIntegerField(default=0)),
                ('rounds_lost', models.PositiveSmallIntegerField(default=0)),
                ('avg_rating', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('total_rating', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('entries', models.IntegerField(default=0)),
                ('rounds', models.IntegerField(default=0)),
                ('avg_damage', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MatchReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('proof', models.CharField(default='no text inserted', max_length=300)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchreporting', to='matches.match')),
            ],
        ),
    ]
