# Generated by Django 4.2.5 on 2023-10-02 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchreport',
            name='reported_winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winnerreporting', to='teams.team'),
        ),
        migrations.AddField(
            model_name='matchreport',
            name='reporting_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teamreporting', to='teams.team'),
        ),
        migrations.AddField(
            model_name='matchreport',
            name='reporting_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userreporting', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matchdispute',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputedMatch', to='matches.match'),
        ),
        migrations.AddField(
            model_name='matchdispute',
            name='team1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team1', to='teams.team'),
        ),
        migrations.AddField(
            model_name='matchdispute',
            name='team1origreporter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team1OriginalReporter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matchdispute',
            name='team2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team2', to='teams.team'),
        ),
        migrations.AddField(
            model_name='matchdispute',
            name='team2origreporter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team2OriginalReporter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matchdispute',
            name='teamreporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team1Disputer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matchcheckin',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_checkin', to='matches.match'),
        ),
        migrations.AddField(
            model_name='matchcheckin',
            name='reporter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkin_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matchcheckin',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checking_in_team', to='teams.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='awayteam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awayteam', to='teams.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition', to='competitions.competition'),
        ),
        migrations.AddField(
            model_name='match',
            name='hometeam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hometeam', to='teams.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='loser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loser', to='teams.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='map_pool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mappoolchoice', to='matches.mappoolchoice'),
        ),
        migrations.AddField(
            model_name='match',
            name='maps',
            field=models.ManyToManyField(blank=True, to='matches.mapchoice'),
        ),
        migrations.AddField(
            model_name='match',
            name='team1reportedwinner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team1reportedwinner', to='teams.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team2reportedwinner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team2reportedwinner', to='teams.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='champions', to='teams.team'),
        ),
        migrations.AddField(
            model_name='mappoolchoice',
            name='maps',
            field=models.ManyToManyField(blank=True, to='matches.mapchoice'),
        ),
    ]
