# Generated by Django 4.2.5 on 2023-10-06 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='competition',
        ),
    ]
